const UNAUTHORIZED = 'UNAUTHORIZED';
const SIS_401 = 'SIS-401';
const ROLE_ASSOCIATED = 'SIS-ROLE-001';
const ATTRIBUTE_ASSOCIATED = 'SIS-ATTRIBUTE-001';
const USER_SERVICE_SUSPENSION = 'SIS-USER-001';
const ATTRIBUTE_NAME_EXISTED = 'SIS-ATTRIBUTE-105';

export {
  UNAUTHORIZED,
  SIS_401,
  ROLE_ASSOCIATED,
  ATTRIBUTE_ASSOCIATED,
  USER_SERVICE_SUSPENSION,
  ATTRIBUTE_NAME_EXISTED,
};
